require('plugins')
require('options')
require('mappings')

require('autopairs-config')
require('blamer-config')
require('bufferline-config')
require('coc-config')
require('floaterm-config')
require('fugitive-config')
require('nord-config')
require('nvim-lualine-config')
require('nvim-tree-config')
require('nvim-treesitter-config')
-- require('rainbow-config')
require('telescope-config')
require('vim-projectionist-config')
require('vim-test-config')
require('which-key-config')
